### ISSUE TITLE
Release v1.2.0

### ISSUE THREAD

**Issue by marian13** [nhocki/version_gemfile#4]
Hi @nhocki, I would like to ask you - do you have any plans to release a new 1.2.0 version and push it to RubyGems?

Currently, I am using a fork in all my projects like so:

```
gem "version_gemfile", "~> 1.1.0", git: "https://github.com/marian13/version_gemfile", branch: "development"
```
After release, it can be updated to:

```
gem "version_gemfile", "~> 1.2.0"
```

Thank you for all the hard work you did to create this gem 🚀 .

**Comment by nhocki** [comment]
@marian13 I've released a new version! Thanks!

https://rubygems.org/gems/version_gemfile
